[versions]
agp = "7.0.4"
lint = "30.0.4" # 始终等于 agp + 23
kotlin = { strictly = "1.5.31" }
kotlin-json = { strictly = "1.3.0" } # uses Kotlin 1.5.31 as default.
compose = "1.0.5"
retrofit = "2.9.0"
coroutinue = "1.3.4"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
sqldelight = { id = "com.squareup.sqldelight", version = "1.5.3" }
compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.11.0" }

[libraries]
# androidx
material = "com.google.android.material:material:1.4.0"
androidx-ktx = "androidx.core:core-ktx:1.7.0"
lifecycle-ktx = "androidx.lifecycle:lifecycle-runtime-ktx:2.4.0"
datastore = "androidx.datastore:datastore:1.0.0"
datastore-preferences = "androidx.datastore:datastore-preferences:1.0.0"
activity-ktx = "androidx.activity:activity-ktx:1.1.0"
fragment-ktx = "androidx.fragment:fragment-ktx:1.2.5"
viewmodel-ktx = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.2.0"
livedata-ktx = "androidx.lifecycle:lifecycle-livedata-ktx:2.2.0"
lifecycle-service = "androidx.lifecycle:lifecycle-service:2.3.1"

# deprecated(replaced by compose)
constraintlayout = "androidx.constraintlayout:constraintlayout:1.1.3"
appcompat = 'androidx.appcompat:appcompat:1.0.2'
recyclerview = 'androidx.recyclerview:recyclerview:1.2.0'

# compose
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
activity-compose = "androidx.activity:activity-compose:1.3.1"

# third-party
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
coroutinue-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutinue" }
coroutinue-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutinue" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlin-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-json" }

logcat = "com.squareup.logcat:logcat:0.1"
coil = "io.coil-kt:coil-compose:1.4.0"
koin = "io.insert-koin:koin-android:3.1.4"
sql = "com.squareup.sqldelight:android-driver:1.5.3"
toast = "me.drakeet.support:toastcompat:1.1.0"

# foodiestudio
ctc = "com.github.kkoshin:ctc:0.1.1"
dev-tools = "com.github.foodiestudio:dev-tools:0.0.1"
sugar = "com.github.foodiestudio:sugar:0.0.1-rc.8"
theme = "com.github.foodiestudio:app-theme:0.1.3"

# lint
lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "lint" }
lint-checks = { module = "com.android.tools.lint:lint-checks", version.ref = "lint" }
lint-core = { module = "com.android.tools.lint:lint", version.ref = "lint" }
lint-tests = { module = "com.android.tools.lint:lint-tests", version.ref = "lint" }

# for test
junit = "junit:junit:4.+"
junit-android = "androidx.test.ext:junit:1.1.3"
junit-compose = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
espresso = "androidx.test.espresso:espresso-core:3.4.0"

[bundles]
jetpack = ["androidx-ktx", "material", "lifecycle-ktx", "datastore", "datastore-preferences"]
jetpack-ktx = ["activity-ktx", "fragment-ktx", "viewmodel-ktx", "livedata-ktx"]
kotlin = ["kotlin-stdlib", "kotlin-json", "coroutinue-core", "coroutinue-android"]
compose = ["compose-ui", "compose-material", "activity-compose", "compose-livedata"]
network = ["retrofit", "retrofit-converter-gson"]
foodiestudio = ["sugar", "theme"]
debug = ["compose-ui-tooling", "dev-tools"]
unit-tests = ["junit"]
android-tests = ["junit-android", "junit-compose", "espresso"]
lint = ["lint-api", "lint-checks"]
lint-test = ["lint-core", "lint-tests"]
