[versions]
# langauge and platform
kotlin = "1.8.0"

[plugins]
compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.11.0" }

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }

[bundles]
